name: Pre-Commit
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Check merge conflicts
        run: pre-commit run check-merge-conflict --all-files --verbose
      - name: Check large files
        run: pre-commit run check-added-large-files --all-files --verbose
      - name: Check final newlines
        run: pre-commit run end-of-file-fixer --all-files --verbose
      - name: Check trailing whitespace
        run: pre-commit run trailing-whitespace --all-files --verbose
      - name: Check line endings
        run: pre-commit run mixed-line-ending --all-files --verbose
      - name: Check YAML
        run: pre-commit run check-yaml --all-files --verbose
